alter table US_WATERMETER_INFO add reversal_counts NUMBER(4) default 0;
alter table US_WATERMETER_INFO add REVERSAL_DIRECTION NUMBER(1) ;

drop index UIDX_BS_ORI_NW_DATE_USED ;
Create  index UIDX_BS_ORI_NW_DATE_USED on BS_ORIGINALDATA(IS_NEW, WATER_METER_ID, DATA_DATE, TOTAL_USED) tablespace ECMS_INDEX ;


drop index UIDX_BS_ORI_NEW_WATER ;
Create  index UIDX_BS_ORI_NEW_WATER  on BS_ORIGINALDATA(IS_NEW, WATER_METER_ID) tablespace ECMS_INDEX ;

drop index UIDX_BS_ORI_WATER_NEW_USED ;
Create  index UIDX_BS_ORI_WATER_NEW_USED on BS_ORIGINALDATA(WATER_METER_ID, IS_NEW, TOTAL_USED) tablespace ECMS_INDEX ;
