
spool table.log
prompt
prompt drop table 
prompt =============================
prompt
prompt Dropping ECMS.SYS_ALARM_CODE...
drop table ECMS.SYS_ALARM_CODE cascade constraints;
prompt Dropping ECMS.US_ALARM_PROCESS_INFOR...
drop table ECMS.US_ALARM_PROCESS_INFOR cascade constraints;
prompt Dropping ECMS.US_USER_INFOR...
drop table ECMS.US_USER_INFOR cascade constraints;
prompt Dropping ECMS.BS_ALARM_INFOR...
drop table ECMS.BS_ALARM_INFOR cascade constraints;
prompt Dropping ECMS.BS_ALERM_SYSRECEIVER...
drop table ECMS.BS_ALERM_SYSRECEIVER cascade constraints;
prompt Dropping ECMS.US_BALANCE_SET...
drop table ECMS.US_BALANCE_SET cascade constraints;
prompt Dropping ECMS.BS_BALANCE_RECORD...
drop table ECMS.BS_BALANCE_RECORD cascade constraints;
prompt Dropping ECMS.US_SERVER_INFOR...
drop table ECMS.US_SERVER_INFOR cascade constraints;
prompt Dropping ECMS.US_GATEWAY_INFOR...
drop table ECMS.US_GATEWAY_INFOR cascade constraints;
prompt Dropping ECMS.US_METERLEVEL...
drop table ECMS.US_METERLEVEL cascade constraints;
prompt Dropping ECMS.US_METER_MEASURE...
drop table ECMS.US_METER_MEASURE cascade constraints;
prompt Dropping ECMS.US_ADDR_ORG_LEVEL...
drop table ECMS.US_ADDR_ORG_LEVEL cascade constraints;
prompt Dropping ECMS.US_ORGAN_INFOR...
drop table ECMS.US_ORGAN_INFOR cascade constraints;
prompt Dropping ECMS.US_PHYSICAL_ADDRESS...
drop table ECMS.US_PHYSICAL_ADDRESS cascade constraints;
prompt Dropping ECMS.US_COM_INFOR...
drop table ECMS.US_COM_INFOR cascade constraints;
prompt Dropping ECMS.US_ZWJ...
drop table ECMS.US_ZWJ cascade constraints;
prompt Dropping ECMS.SYS_METER_TYPE...
drop table ECMS.SYS_METER_TYPE cascade constraints;
prompt Dropping ECMS.US_ELECMETER_INFO...
drop table ECMS.US_ELECMETER_INFO cascade constraints;
prompt Dropping ECMS.US_GASMETER_INFO...
drop table ECMS.US_GASMETER_INFO cascade constraints;
prompt Dropping ECMS.US_WARMMETER_INFO...
drop table ECMS.US_WARMMETER_INFO cascade constraints;
prompt Dropping ECMS.SYS_WATER_METER_CALIBER...
drop table ECMS.SYS_WATER_METER_CALIBER cascade constraints;
prompt Dropping ECMS.US_METER_GROUP...
drop table ECMS.US_METER_GROUP cascade constraints;
prompt Dropping ECMS.US_WATERMETER_INFO...
drop table ECMS.US_WATERMETER_INFO cascade constraints;
prompt Dropping ECMS.BS_INCREMENT_DATA...
drop table ECMS.BS_INCREMENT_DATA cascade constraints;
prompt Dropping ECMS.BS_MID_GATEWAY_BATCH...
drop table ECMS.BS_MID_GATEWAY_BATCH cascade constraints;
prompt Dropping ECMS.BS_ORIGINALDATA...
drop table ECMS.BS_ORIGINALDATA cascade constraints;
prompt Dropping ECMS.BS_TREATEDDATA...
drop table ECMS.BS_TREATEDDATA cascade constraints;
prompt Dropping ECMS.BS_VIRTUAL_ERROR_METER...
drop table ECMS.BS_VIRTUAL_ERROR_METER cascade constraints;
prompt Dropping ECMS.SYS_COLPOINT_CODE...
drop table ECMS.SYS_COLPOINT_CODE cascade constraints;
prompt Dropping ECMS.SYS_FUNCTION...
drop table ECMS.SYS_FUNCTION cascade constraints;
prompt Dropping ECMS.US_ADDR_ORG_PROPERTY...
drop table ECMS.US_ADDR_ORG_PROPERTY cascade constraints;
prompt Dropping ECMS.US_BALANCE_METER...
drop table ECMS.US_BALANCE_METER cascade constraints;
prompt Dropping ECMS.US_BUILDING_CLASSIFY_AREA...
drop table ECMS.US_BUILDING_CLASSIFY_AREA cascade constraints;
prompt Dropping ECMS.US_BUILDING_INFO...
drop table ECMS.US_BUILDING_INFO cascade constraints;
prompt Dropping ECMS.US_COUNT_CLASS_INFO...
drop table ECMS.US_COUNT_CLASS_INFO cascade constraints;
prompt Dropping ECMS.US_DICTIONARY_CONTENT...
drop table ECMS.US_DICTIONARY_CONTENT cascade constraints;
prompt Dropping ECMS.US_DICTIONARY_TYPE...
drop table ECMS.US_DICTIONARY_TYPE cascade constraints;
prompt Dropping ECMS.US_MESSAGE_RECEIVE...
drop table ECMS.US_MESSAGE_RECEIVE cascade constraints;
prompt Dropping ECMS.US_MESSAGE_SEND...
drop table ECMS.US_MESSAGE_SEND cascade constraints;
prompt Dropping ECMS.US_METER_COUNT_CLASS...
drop table ECMS.US_METER_COUNT_CLASS cascade constraints;
prompt Dropping ECMS.US_MID_ADDR_PROPERTY...
drop table ECMS.US_MID_ADDR_PROPERTY cascade constraints;
prompt Dropping ECMS.US_MID_COLPOINT_METERTYPE...
drop table ECMS.US_MID_COLPOINT_METERTYPE cascade constraints;
prompt Dropping ECMS.US_ROLE...
drop table ECMS.US_ROLE cascade constraints;
prompt Dropping ECMS.US_MID_FUNCTION_ROLE...
drop table ECMS.US_MID_FUNCTION_ROLE cascade constraints;
prompt Dropping ECMS.US_MID_METERTYPE_METERPAR...
drop table ECMS.US_MID_METERTYPE_METERPAR cascade constraints;
prompt Dropping ECMS.US_MID_ORG_PROPERTY...
drop table ECMS.US_MID_ORG_PROPERTY cascade constraints;
prompt Dropping ECMS.US_MID_USER_ROLE...
drop table ECMS.US_MID_USER_ROLE cascade constraints;
prompt Dropping ECMS.US_OLD_METER_INFO...
drop table ECMS.US_OLD_METER_INFO cascade constraints;
prompt Dropping ECMS.US_RUNTIME_PAR...
drop table ECMS.US_RUNTIME_PAR cascade constraints;
prompt Dropping ECMS.US_SHORTCUT_MENU...
drop table ECMS.US_SHORTCUT_MENU cascade constraints;
prompt Dropping ECMS.US_TIMETASK...
drop table ECMS.US_TIMETASK cascade constraints;
prompt Dropping ECMS.US_VIRTUAL_COMPUTE...
drop table ECMS.US_VIRTUAL_COMPUTE cascade constraints;
prompt Dropping ECMS.US_MID_VIRTUAL_USER...
drop table ECMS.US_MID_VIRTUAL_USER cascade constraints;
prompt Dropping ECMS.US_ORGAN_QUOTA...
drop table ECMS.US_ORGAN_QUOTA cascade constraints;
prompt Dropping ECMS.US_ORGAN_ADD_QUOTA...
drop table ECMS.US_ORGAN_ADD_QUOTA cascade constraints;
prompt Dropping ECMS.US_MODIFY_QUOTA_RECORD...
drop table ECMS.US_MODIFY_QUOTA_RECORD cascade constraints;
prompt Dropping ECMS.US_ENERGY_LIMIT_ALARM...
drop table ECMS.US_ENERGY_LIMIT_ALARM cascade constraints;
prompt Dropping ECMS.US_UDP_INFO...
drop table ECMS.US_UDP_INFO cascade constraints;
prompt Dropping ECMS.US_OPERATE_LOG...
drop table ECMS.US_OPERATE_LOG cascade constraints;

prompt Dropping ECMS.US_PERSONNEL_INFOR...
drop table ECMS.US_PERSONNEL_INFOR cascade constraints;
prompt Dropping ECMS.US_EQUIPMENT_INFOR...
drop table ECMS.US_EQUIPMENT_INFOR cascade constraints;
prompt Dropping ECMS.US_REPORT_SET...
drop table ECMS.US_REPORT_SET cascade constraints;
prompt Dropping ECMS.US_SCHOOL_INFO...
drop table ECMS.US_SCHOOL_INFO cascade constraints;
prompt Dropping ECMS.US_QUOTA...
drop table ECMS.US_QUOTA cascade constraints;
prompt Dropping ECMS.US_MODIFY_QUOTA...
drop table ECMS.US_MODIFY_QUOTA cascade constraints;
prompt Dropping ECMS.US_MAPSET_INFOR...
drop table ECMS.US_MAPSET_INFOR cascade constraints;
prompt Dropping ECMS.US_METER_CONTROL...
drop table ECMS.US_METER_CONTROL cascade constraints;


prompt Creating ECMS.SYS_ALARM_CODE...
create table ECMS.SYS_ALARM_CODE
(
  ID          CHAR(32) not null,
  ALARM_TYPE  NUMBER(4) not null,
  ALARM_LEVEL NUMBER(4) not null,
  CODE        VARCHAR2(10) not null,
  INFOR       VARCHAR2(100) not null
)
;
alter table ECMS.SYS_ALARM_CODE
  add constraint PK_SYS_ALARM_CODE primary key (ID);

prompt Creating ECMS.US_ALARM_PROCESS_INFOR...
create table ECMS.US_ALARM_PROCESS_INFOR
(
  ID         CHAR(32) not null,
  CODE       VARCHAR2(10),
  REMARK     VARCHAR2(200) not null,
  ALARM_TYPE NUMBER(4)
)
;
alter table ECMS.US_ALARM_PROCESS_INFOR
  add constraint PK_US_ALARM_PROCESS_INFOR primary key (ID);

prompt Creating ECMS.US_USER_INFOR...
create table ECMS.US_USER_INFOR
(
  ID          CHAR(32) not null,
  NAME        VARCHAR2(60) not null,
  PASSWORD    VARCHAR2(20) not null,
  CREATE_DATE VARCHAR2(19) not null,
  MODIFY_DATE VARCHAR2(19),
  USERNAME    VARCHAR2(60),
  TELEPHONE   VARCHAR2(20),
  EMAIL       VARCHAR2(30),
  IS_DISABLE  CHAR(1) not null
)
;
alter table ECMS.US_USER_INFOR
  add constraint PK_US_USER_INFOR primary key (ID);

prompt Creating ECMS.BS_ALARM_INFOR...
create table ECMS.BS_ALARM_INFOR
(
  ID               CHAR(32) not null,
  METER_ID         CHAR(32),
  ALARM_DATE       VARCHAR2(19),
  PROCESS_INFOR_ID CHAR(32),
  ALARM_INFOR_ID   CHAR(32),
  PROCESS_DATE     VARCHAR2(19),
  PROCESSOR        CHAR(32),
  REMARK           VARCHAR2(200),
  MIDMACHINE_ID    CHAR(32),
  ADDR_ID          CHAR(32),
  GATEWAY_ID       CHAR(32),
  BALANCE_ID       CHAR(32),
  ORG_ID		   CHAR(32)
)
;
alter table ECMS.BS_ALARM_INFOR
  add constraint PK_BS_ALARM_INFOR primary key (ID);


prompt Creating ECMS.BS_ALERM_SYSRECEIVER...
create table ECMS.BS_ALERM_SYSRECEIVER
(
  ID             CHAR(32) default SYS_guid() not null,
  ALARM_INFOR_ID CHAR(32) not null,
  USER_ID        CHAR(32) not null
)
;
alter table ECMS.BS_ALERM_SYSRECEIVER
  add constraint PK_BS_ALERM_SYSRECEIVER primary key (ID);


prompt Creating ECMS.US_BALANCE_SET...
create table ECMS.US_BALANCE_SET
(
  ID           CHAR(32) not null,
  BALANCE_NAME VARCHAR2(15 CHAR),
  BALANCE_AREA VARCHAR2(15 CHAR),
  REMARK       NVARCHAR2(50),
  PERCENT      NUMBER(5,2),
  CREATE_DATE  VARCHAR2(19),
  MODIFY_DATE  VARCHAR2(19),
  BALANCE_TYPE NUMBER(10)
)
;
alter table ECMS.US_BALANCE_SET
  add constraint PK_US_BALANCE_INIT primary key (ID);


prompt Creating ECMS.BS_BALANCE_RECORD...
create table ECMS.BS_BALANCE_RECORD
(
  ID            CHAR(32),
  BALANCE_ID    CHAR(32),
  BALANCE_VALUE NUMBER(5,2),
  BALANCE_TIME  CHAR(19)
)
;
alter table ECMS.BS_BALANCE_RECORD
  add constraint PK_BS_BALANCE_RECORD primary key (ID);

prompt Creating ECMS.US_SERVER_INFOR...
create table ECMS.US_SERVER_INFOR
(
  ID         CHAR(32) not null,
  IP_ADDRESS VARCHAR2(15) not null,
  IP_PORT    VARCHAR2(4) not null,
  REMARK     VARCHAR2(100),
  SHOWNAME   VARCHAR2(60) not null
)
;
alter table ECMS.US_SERVER_INFOR
  add constraint PK_US_SERVER_INFOR primary key (ID);

prompt Creating ECMS.US_GATEWAY_INFOR...
create table ECMS.US_GATEWAY_INFOR
(
  ID             CHAR(32) not null,
  IP_ADDRESS     VARCHAR2(15),
  REMARK         VARCHAR2(200),
  SERVER_ID      CHAR(32),
  SHOWNAME       VARCHAR2(40),
  IP_PORT        NUMBER(4),
  OFF_POWER_TIME CHAR(5),
  ON_POWER_TIME  CHAR(5),
  IS_OFF_POWER   CHAR(1)
)
;
alter table ECMS.US_GATEWAY_INFOR
  add constraint PK_US_GATEWAY_INFOR primary key (ID);


prompt Creating ECMS.US_METERLEVEL...
create table ECMS.US_METERLEVEL
(
  ID             CHAR(32) not null,
  SHOWNAME       VARCHAR2(10) not null,
  METER_CLASSIFY NUMBER(2)
)
;
alter table ECMS.US_METERLEVEL
  add constraint PK_US_METERLEVEL primary key (ID);

prompt Creating ECMS.US_METER_MEASURE...
create table ECMS.US_METER_MEASURE
(
  ID              CHAR(32) not null,
  SHOWNAME        VARCHAR2(60) not null,
  METER_CLASSSIFY NUMBER(2)
)
;
alter table ECMS.US_METER_MEASURE
  add constraint PK_US_METER_MEASURE primary key (ID);

prompt Creating ECMS.US_ADDR_ORG_LEVEL...
create table ECMS.US_ADDR_ORG_LEVEL
(
  LEVEL_CODE   NUMBER(3) not null,
  LEVEL_NAME   NVARCHAR2(60),
  LEVEL_NUMBER NUMBER(2),
  LEVEL_TYPE   NUMBER(1)
)
;
alter table ECMS.US_ADDR_ORG_LEVEL
  add constraint PK_US_ADDR_ORG_LEVEL primary key (LEVEL_CODE);

prompt Creating ECMS.US_ORGAN_INFOR...
create table ECMS.US_ORGAN_INFOR
(
  ORG_ID       CHAR(32) not null,
  SUPER_ORG_ID CHAR(32),
  ORG_NAME     VARCHAR2(60),
  CREATE_DATE  VARCHAR2(19),
  MODIFY_DATE  VARCHAR2(19),
  ORG_CODE     VARCHAR2(18),
  ORG_AREA     NUMBER(10,2),
  ORG_NUMBER   VARCHAR2(50),
  PEOPLE_COUNT NUMBER(9),
  ORGER        NVARCHAR2(10),
  LEVEL_CODE   NUMBER(3),
  ORGER_PHONE  NVARCHAR2(30),
  REMARK       NVARCHAR2(100),
  IF_CHANGE_METER NUMBER(1) default 0,
  RESEARCHE_FUNDING number(14,2)
)
;
alter table ECMS.US_ORGAN_INFOR
  add constraint PK_US_ORGAN_INFOR primary key (ORG_ID);


prompt Creating ECMS.US_PHYSICAL_ADDRESS...
create table ECMS.US_PHYSICAL_ADDRESS
(
  ADDR_ID       CHAR(32) not null,
  SUPER_ADDR_ID CHAR(32),
  ADDR_NAME     VARCHAR2(60) not null,
  ADDR_CODE     VARCHAR2(15),
  CREATE_DATE   VARCHAR2(19),
  MODIFY_DATE   VARCHAR2(19),
  ADDR_AREA     NUMBER(10,2),
  LEVEL_CODE    NUMBER(3),
  PEOPLE_COUNT  NUMBER(9),
  BUILDER       NVARCHAR2(10),
  BUIDER_PHONE  VARCHAR2(30),
  REMARK        NVARCHAR2(100),
  ADDR_NUMBER   VARCHAR2(50),
  BUILDER_PHONE VARCHAR2(255 CHAR),
  COMMUTED_PEOCOUNT  NUMBER(9),
  BUILD_TYPE        CHAR(1),
  BUILD_HEIGHT      NUMBER(10,2),
  BUILD_FLOOR       NUMBER(2),
  BUILTED_YEAR      CHAR(4),
  STU_COUNT         NUMBER(8),
  TEACHER_COUNT     NUMBER(8),
  ECONOMY_TARGET    number(14,2)
)
;
alter table ECMS.US_PHYSICAL_ADDRESS
  add constraint PK_US_PHYSICAL_ADDRESS primary key (ADDR_ID);


prompt Creating ECMS.US_COM_INFOR...
create table ECMS.US_COM_INFOR
(
  ID           CHAR(32) not null,
  SHOWNAME     VARCHAR2(50),
  GATEWAY_ID   CHAR(32),
  IS_DISABLE   CHAR(1),
  REMARK       VARCHAR2(100),
  COM_NUMBER   NUMBER(3),
  COM_NAME     VARCHAR2(20),
  INTERMISSION NUMBER(6),
  TOGATEWAY    CHAR(1)
)
;
alter table ECMS.US_COM_INFOR
  add constraint PK_US_COM_INFOR primary key (ID);


prompt Creating ECMS.US_ZWJ...
create table ECMS.US_ZWJ
(
  PK_ZWJ    CHAR(32) not null,
  SERIALNO  VARCHAR2(50 CHAR),
  ADDRESS   VARCHAR2(50 CHAR),
  PK_COM    CHAR(32),
  BAND_RATE NUMBER(6),
  PARITY    NUMBER(1),
  STOPBITS  NUMBER(1),
  DATABITS  NUMBER(2),
  REMARK    VARCHAR2(50 CHAR),
  SHOW_NAME VARCHAR2(50 CHAR),
  TOGATEWAY CHAR(1),
  ADDR_ID   CHAR(32),
  PK_UDP_INFO CHAR(32)
)
;
alter table ECMS.US_ZWJ
  add constraint PK_ZWJ primary key (PK_ZWJ);


prompt Creating ECMS.SYS_METER_TYPE...
create table ECMS.SYS_METER_TYPE
(
  ID             CHAR(32) not null,
  SHOWNAME       VARCHAR2(60) not null,
  METER_CLASSIFY NUMBER(2),
  CODE           NUMBER(2)
)
;
alter table ECMS.SYS_METER_TYPE
  add constraint PK_SYS_METER_TYPE primary key (ID);

prompt Creating ECMS.US_ELECMETER_INFO...
create table ECMS.US_ELECMETER_INFO
(
  METER_ID           CHAR(32) not null,
  METER_SERIALNUMBER VARCHAR2(25),
  SUPER_METER_ID     CHAR(32),
  METER_TYPE_ID      CHAR(32),
  METER_MEASURE_ID   CHAR(32),
  METER_PROPERTYTYPE_ID  CHAR(32),
  METER_LEVEL_ID     CHAR(32),
  GATEWAY_ID         CHAR(32),
  COM_ID             CHAR(32),
  IS_DISABLE         CHAR(1),
  IS_DELETE          CHAR(1),
  METER_NAME         VARCHAR2(60 CHAR) not null,
  ADDR_ID            CHAR(32),
  ORG_ID             CHAR(32),
  ACCOUNT_ID         CHAR(32),
  VIRTUAL_REAL_TYPE  CHAR(1) not null,
  SERVER_ID          CHAR(32),
  CREATE_DATE        VARCHAR2(19),
  MODIFY_DATE        VARCHAR2(19),
  BAUD_BIT           NUMBER(6),
  STOP_BIT           NUMBER(1),
  DATA_BIT           NUMBER(1),
  CHECK_BIT          NUMBER(1),
  POLL_INTERVAL      NUMBER(4),
  ADDR_STAT_AREA     NUMBER(2),
  ORG_STAT_AREA      NUMBER(2),
  MID_MACHINE_ID     CHAR(32),
  MID_MACHINE_PORT   NUMBER(4),
  METER_ADDR         VARCHAR2(12),
  REMARK             VARCHAR2(100 CHAR),
  INITVALUE          NUMBER(10,2),
  INITDATE           CHAR(19),
  MULTIPLE           NUMBER(4),
  ADDRESSSETTED      CHAR(1),
  PERCENT            NUMBER(4,2),
  IS_INIT            CHAR(1),
  CHANGE_VALUE       NUMBER(10,2),
  VIRTUAL_COUNT_TYPE NUMBER(1),
  PK_UDP_INFO        CHAR(32),
  is_count              CHAR(1) default 'N',
  IS_VALUE           CHAR(1)
)
;
alter table ECMS.US_ELECMETER_INFO
  add constraint PK_US_METER_INFO primary key (METER_ID);


prompt Creating ECMS.US_GASMETER_INFO...
create table ECMS.US_GASMETER_INFO
(
  METER_ID           CHAR(32) not null,
  METER_SERIALNUMBER VARCHAR2(25),
  SUPER_METER_ID     CHAR(32),
  METER_TYPE_ID      CHAR(32),
  METER_MEASURE_ID   CHAR(32),
  METER_LEVEL_ID     CHAR(32),
  GATEWAY_ID         CHAR(32),
  COM_ID             CHAR(32),
  IS_DISABLE         CHAR(1),
  IS_DELETE          CHAR(1),
  METER_NAME         VARCHAR2(60),
  ADDR_ID            CHAR(32),
  ORG_ID             CHAR(32),
  VIRTUAL_REAL_TYPE  NUMBER(1),
  SERVER_ID          CHAR(32),
  CREATE_DATE        VARCHAR2(19),
  MODIFY_DATE        VARCHAR2(19),
  BAUD_BIT           NUMBER(6),
  STOP_BIT           NUMBER(1),
  DATA_BIT           NUMBER(1),
  CHECK_BIT          NUMBER(1),
  POLL_INTERVAL      NUMBER(4),
  ADDR_STAT_AREA     NUMBER(2),
  ORG_STAT_AREA      NUMBER(2),
  METER_ADDR         VARCHAR2(12),
  INITVALUE          NUMBER(11,3),
  INITDATE           NUMBER(11,3),
  MULTIPLE           NUMBER(4),
  ADDRESSSETTED      CHAR(1),
  REMARK             NVARCHAR2(100),
  PERCENT            NUMBER(4,2),
  IS_INIT            CHAR(1),
  CHANGE_VALUE       NUMBER(11,3),
  VIRTUAL_COUNT_TYPE CHAR(1)
)
;
alter table ECMS.US_GASMETER_INFO
  add constraint PK_US_GASMETER_INFO primary key (METER_ID);


prompt Creating ECMS.US_WARMMETER_INFO...
create table ECMS.US_WARMMETER_INFO
(
  METER_ID           CHAR(32) not null,
  METER_SERIALNUMBER VARCHAR2(25),
  METER_TYPE_ID      CHAR(32),
  SUPER_METER_ID     CHAR(32),
  METER_MEASURE_ID   CHAR(32),
  METER_LEVEL_ID     CHAR(32),
  GATEWAY_ID         CHAR(32),
  COM_ID             CHAR(32),
  IS_DISABLE         CHAR(1),
  IS_DELETE          CHAR(1),
  METER_NAME         VARCHAR2(60),
  ADDR_ID            CHAR(32),
  ORG_ID             CHAR(32),
  VIRTUAL_REAL_TYPE  NUMBER(1),
  SERVER_ID          CHAR(32),
  CREATE_DATE        VARCHAR2(19),
  BAUD_BIT           NUMBER(6),
  STOP_BIT           NUMBER(1),
  DATA_BIT           NUMBER(1),
  CHECK_BIT          NUMBER(1),
  POLL_INTERVAL      NUMBER(4),
  ADDR_STAT_AREA     NUMBER(2),
  ORG_STAT_AREA      NUMBER(2),
  METER_ADDR         VARCHAR2(12),
  INITVALUE          NUMBER(11,3),
  INITDATE           NUMBER(11,3),
  MULTIPLE           NUMBER(4),
  ADDRESSSETTED      CHAR(1),
  REMARK             NVARCHAR2(100),
  PERCENT            NUMBER(4,2),
  ISINIT             CHAR(1),
  CHANGEVALUE        NUMBER(11,3),
  VIRTUALCOUNTTYPE   CHAR(1),
  MODIFY_DATE        VARCHAR2(19),
  IS_INIT            VARCHAR2(1 CHAR),
  CHANGE_VALUE       FLOAT,
  VIRTUAL_COUNT_TYPE NUMBER(10)
)
;
alter table ECMS.US_WARMMETER_INFO
  add constraint PK_US_WARMMETER_INFO primary key (METER_ID);


prompt Creating ECMS.SYS_WATER_METER_CALIBER...
create table ECMS.SYS_WATER_METER_CALIBER
(
  ID             CHAR(32) not null,
  CALIBER        NVARCHAR2(20),
  MEASURING_UNIT NUMBER(8,3)
)
;
alter table ECMS.SYS_WATER_METER_CALIBER
  add constraint PK_SYS_WATER_METER_CALIBER primary key (ID);

prompt Creating ECMS.US_METER_GROUP...
create table ECMS.US_METER_GROUP
(
  GROUP_NAME     NVARCHAR2(15),
  SUPER_GROUP_ID CHAR(32),
  METER_CLASSIFY NUMBER(2),
  GROUP_ID       CHAR(32) not null
)
;
alter table ECMS.US_METER_GROUP
  add constraint PK_US_METER_GROUP primary key (GROUP_ID);

prompt Creating ECMS.US_WATERMETER_INFO...
create table ECMS.US_WATERMETER_INFO
(
  METER_ID           CHAR(32) not null,
  METER_SERIALNUMBER VARCHAR2(25),
  METER_TYPE_ID      CHAR(32),
  METER_MEASURE_ID   CHAR(32),
  METER_LEVEL_ID     CHAR(32),
  GATEWAY_ID         CHAR(32),
  COM_ID             CHAR(32),
  IS_DISABLE         CHAR(1),
  IS_DELETE          CHAR(1),
  METER_NAME         VARCHAR2(60) not null,
  ADDR_ID            CHAR(32),
  ORG_ID             CHAR(32),
  ACCOUNT_ID         CHAR(32),
  VIRTUAL_REAL_TYPE  NUMBER(1) not null,
  SERVER_ID          CHAR(32),
  CREATE_DATE        VARCHAR2(19),
  MODIFY_DATE        VARCHAR2(19),
  BAUD_BIT           NUMBER(6),
  STOP_BIT           NUMBER(1),
  DATA_BIT           NUMBER(1),
  CHECK_BIT          NUMBER(1),
  POLL_INTERVAL      NUMBER(4),
  ADDR_STAT_AREA     NUMBER(2),
  ORG_STAT_AREA      NUMBER(2),
  METER_ADDR         VARCHAR2(16),
  REMARK             VARCHAR2(100 char),
  INITVALUE          NUMBER(11,3),
  INITDATE           CHAR(19),
  MULTIPLE           NUMBER(4),
  ADDRESSSETTED      CHAR(1),
  PERCENT            NUMBER(4,2),
  GROUP_ID           CHAR(32),
  IS_INIT            CHAR(1),
  CALIBER_ID         CHAR(32),
  CHANGE_VALUE       NUMBER(11,3),
  VIRTUAL_COUNT_TYPE NUMBER(1),
  PK_UDP_INFO        CHAR(32)
)
;
alter table ECMS.US_WATERMETER_INFO
  add constraint PK_US_WATERMETER_INFO primary key (METER_ID);


prompt Creating ECMS.BS_INCREMENT_DATA...
create table BS_INCREMENT_DATA
(
  ID              CHAR(32) not null,
  ELEC_METER_ID   CHAR(32),
  WATER_METER_ID  CHAR(32),
  WARM_METER_ID   CHAR(32),
  GAS_METER_ID    CHAR(32),
  DATA_TYPE       NUMBER(1),
  DATA_TIME       CHAR(19),
  INCREMENT_VALUE NUMBER(13,3),
  ERROR_TYPE      NUMBER(1)
);

alter table ECMS.BS_INCREMENT_DATA
  add constraint PK_BS_TIMEINCREMENT_DATA primary key (ID);


prompt Creating ECMS.BS_MID_GATEWAY_BATCH...
create table ECMS.BS_MID_GATEWAY_BATCH
(
  ID         CHAR(32) not null,
  GATEWAY_ID CHAR(32),
  BATCH      VARCHAR2(32)
)
;
alter table ECMS.BS_MID_GATEWAY_BATCH
  add constraint PK_BS_MID_GATEWAY_BATCH primary key (ID);

prompt Creating ECMS.BS_ORIGINALDATA...
create table BS_ORIGINALDATA
(
  DATA_ID            CHAR(32) not null,
  ELEC_METER_ID      CHAR(32),
  COL_DATE           VARCHAR2(19) not null,
  REPORT_DATE        VARCHAR2(19) not null,
  DATA_DATE          VARCHAR2(19),
  IS_NEW             CHAR(1),
  WATER_METER_ID     CHAR(32),
  WARM_METER_ID      CHAR(32),
  GAS_METER_ID       CHAR(32),
  ERROR_COUNTER      NUMBER(4),
  RIGHT_COUNTER      NUMBER(4),
  TOTAL_USED         NUMBER(13,3),
  TOTAL_BUY          NUMBER(13,3),
  VOLTAGE            NUMBER(4,1),
  ELECTRIC_CURRENT   NUMBER(8,3),
  POWER              NUMBER(10,4),
  A_VOLTAGE          NUMBER(4,1),
  B_VOLTAGE          NUMBER(4,1),
  C_VOLTAGE          NUMBER(4,1),
  A_ELECTRIC_CURRENT NUMBER(8,3),
  B_ELECTRIC_CURRENT NUMBER(8,3),
  C_ELECTRIC_CURRENT NUMBER(8,3),
  A_POWER            NUMBER(7,4),
  B_POWER            NUMBER(7,4),
  C_POWER            NUMBER(7,4),
  BATCHNO            CHAR(32)
);
alter table ECMS.BS_ORIGINALDATA
  add constraint PK_BS_ORIGINALDATA primary key (DATA_ID);


prompt Creating ECMS.BS_TREATEDDATA...
create table BS_TREATEDDATA
(
  DATA_ID            CHAR(32) not null,
  ELEC_METER_ID      CHAR(32),
  TREATE_DATE        VARCHAR2(19) not null,
  WATER_METER_ID     CHAR(32),
  WARM_METER_ID      CHAR(32),
  GAS_METER_ID       CHAR(32),
  ERROR_COUNTER      NUMBER(4),
  RIGHT_COUNTER      NUMBER(4),
  TOTAL_USED         NUMBER(13,3),
  TOTAL_BUY          NUMBER(13,3),
  VOLTAGE            NUMBER(4,1),
  ELECTRIC_CURRENT   NUMBER(8,3),
  POWER              NUMBER(10,4),
  A_VOLTAGE          NUMBER(4,1),
  B_VOLTAGE          NUMBER(4,1),
  C_VOLTAGE          NUMBER(4,1),
  A_ELECTRIC_CURRENT NUMBER(8,3),
  B_ELECTRIC_CURRENT NUMBER(8,3),
  C_ELECTRIC_CURRENT NUMBER(8,3),
  A_POWER            NUMBER(7,4),
  B_POWER            NUMBER(7,4),
  C_POWER            NUMBER(7,4),
  ERROR_TYPE         NUMBER(1)
);

alter table ECMS.BS_TREATEDDATA
  add constraint PK_BS_TREATEDDATA primary key (DATA_ID);


prompt Creating ECMS.BS_VIRTUAL_ERROR_METER...
create table ECMS.BS_VIRTUAL_ERROR_METER
(
  ID              CHAR(32) not null,
  TREATED_DATA_ID CHAR(32),
  ELEC_METER_ID   CHAR(32),
  WATER_METER_ID  CHAR(32),
  WARM_METER_ID   CHAR(32),
  GAS_METER_ID    CHAR(32)
)
;
alter table ECMS.BS_VIRTUAL_ERROR_METER
  add constraint PK_BS_VIRTUAL_ERROR_METER primary key (ID);


prompt Creating ECMS.SYS_COLPOINT_CODE...
create table ECMS.SYS_COLPOINT_CODE
(
  ID       CHAR(32) not null,
  SHOWNAME VARCHAR2(60) not null,
  CODE     VARCHAR2(10)
)
;
alter table ECMS.SYS_COLPOINT_CODE
  add constraint PK_SYS_COLPOINT_CODE primary key (ID);

prompt Creating ECMS.SYS_FUNCTION...
create table ECMS.SYS_FUNCTION
(
  ID         CHAR(32) not null,
  SUPER_ID   CHAR(32) not null,
  SHOWNAME   VARCHAR2(60) not null,
  URL        VARCHAR2(60),
  IS_DISABLE CHAR(1) not null,
  CODE       VARCHAR2(10),
  FUN_LEVEL  NUMBER(2) not null
)
;
alter table ECMS.SYS_FUNCTION
  add constraint PK_SYS_FUNCTION primary key (ID);

prompt Creating ECMS.US_ADDR_ORG_PROPERTY...
create table ECMS.US_ADDR_ORG_PROPERTY
(
  PROPERTY_ID   CHAR(32) not null,
  PROPERTY_NAME NVARCHAR2(50),
  PROPERTY_TYPE NUMBER(1)
)
;
alter table ECMS.US_ADDR_ORG_PROPERTY
  add constraint PK_US_ADDR_ORG_CLASSIFY primary key (PROPERTY_ID);

prompt Creating ECMS.US_BALANCE_METER...
create table ECMS.US_BALANCE_METER
(
  ID             CHAR(32) not null,
  BALANCE_ID     CHAR(32),
  ELEC_METER_ID  CHAR(32),
  WATER_METER_ID CHAR(32),
  WARM_METER_ID  CHAR(32),
  GAS_METER_ID   CHAR(32),
  LEVEL_TYPE     NUMBER(1)
)
;
alter table ECMS.US_BALANCE_METER
  add constraint PK_US_BALANCE_METER primary key (ID);


prompt Creating ECMS.US_BUILDING_CLASSIFY_AREA...
create table ECMS.US_BUILDING_CLASSIFY_AREA
(
  ID          CHAR(32) not null,
  BUILDING_ID CHAR(32),
  MEASURE_ID  CHAR(32),
  AREA_VALUE  NUMBER(10,2)
)
;
alter table ECMS.US_BUILDING_CLASSIFY_AREA
  add constraint PK_US_BUILDING_AREA primary key (ID);


prompt Creating ECMS.US_BUILDING_INFO...
create table ECMS.US_BUILDING_INFO
(
  BUILDID          CHAR(32) not null,
  ADDRID           CHAR(32) not null,
  BUILDNAME        VARCHAR2(60) not null,
  BUILDTYPE        NUMBER(1),
  MASTER           VARCHAR2(60),
  MASTERNUMBER     VARCHAR2(20),
  HIGH             NUMBER(5,2),
  AIRCONDITIONAREA VARCHAR2(12)
)
;

prompt Creating ECMS.US_COUNT_CLASS_INFO...
create table ECMS.US_COUNT_CLASS_INFO
(
  ID               CHAR(32) not null,
  COUNT_CLASS_NAME VARCHAR2(30) not null,
  REMARK           VARCHAR2(100)
)
;
alter table ECMS.US_COUNT_CLASS_INFO
  add constraint PK_US_COUNT_CLASS_INFO primary key (ID);

prompt Creating ECMS.US_DICTIONARY_CONTENT...
create table ECMS.US_DICTIONARY_CONTENT
(
  ID          CHAR(32) not null,
  DIC_TYPE_ID CHAR(32) not null,
  CONTENT     VARCHAR2(40) not null,
  REMARK      VARCHAR2(100)
)
;
alter table ECMS.US_DICTIONARY_CONTENT
  add constraint PK_US_DICTIONARY_CONTENT primary key (ID);

prompt Creating ECMS.US_DICTIONARY_TYPE...
create table ECMS.US_DICTIONARY_TYPE
(
  ID            CHAR(32) not null,
  DIC_TYPE_NAME VARCHAR2(60) not null,
  DIC_TYPE_CODE VARCHAR2(60) not null,
  REMARK        VARCHAR2(100)
)
;
alter table ECMS.US_DICTIONARY_TYPE
  add constraint PK_US_DICTIONARY_TYPE primary key (ID);

prompt Creating ECMS.US_MESSAGE_RECEIVE...
create table ECMS.US_MESSAGE_RECEIVE
(
  ID      CHAR(32) not null,
  MES_ID  CHAR(32) not null,
  USER_ID CHAR(32) not null,
  IS_READ CHAR(1) not null
)
;
alter table ECMS.US_MESSAGE_RECEIVE
  add constraint PK_US_MESSAGE_RECEIVE primary key (ID);

prompt Creating ECMS.US_MESSAGE_SEND...
create table ECMS.US_MESSAGE_SEND
(
  MES_ID             CHAR(32) not null,
  TITLE              VARCHAR2(100) not null,
  CONTENT            VARCHAR2(400) not null,
  MES_TYPE           NUMBER(4),
  SENDER             CHAR(32) not null,
  CREATE_DATE        VARCHAR2(19) not null,
  ATTACHMENT_ADDRESS VARCHAR2(60)
)
;
alter table ECMS.US_MESSAGE_SEND
  add constraint PK_US_MESSAGE_SEND primary key (MES_ID);


prompt Creating ECMS.US_METER_COUNT_CLASS...
create table ECMS.US_METER_COUNT_CLASS
(
  ID             CHAR(32) default SYS_guid() not null,
  COUNT_CLASS_ID CHAR(32) not null,
  PK_METER       CHAR(32) not null
)
;
alter table ECMS.US_METER_COUNT_CLASS
  add constraint PK_US_METER_COUNT_CLASS primary key (ID);

prompt Creating ECMS.US_MID_ADDR_PROPERTY...
create table ECMS.US_MID_ADDR_PROPERTY
(
  PROPERTY_ID CHAR(32) not null,
  ADDR_ID     CHAR(32) not null
)
;
alter table ECMS.US_MID_ADDR_PROPERTY
  add primary key (ADDR_ID, PROPERTY_ID);


prompt Creating ECMS.US_MID_COLPOINT_METERTYPE...
create table ECMS.US_MID_COLPOINT_METERTYPE
(
  ID          CHAR(32) not null,
  IS_COLLECT  CHAR(1) not null,
  METER_TYPE  CHAR(32) not null,
  COLPOINT_ID CHAR(32) not null
)
;
alter table ECMS.US_MID_COLPOINT_METERTYPE
  add constraint PK_US_MID_COLPOINT_METERTYPE primary key (ID);

prompt Creating ECMS.US_MID_VIRTUAL_USER...
create table ECMS.US_MID_VIRTUAL_USER
(
  id                CHAR(32) not null,
  increment_date_id CHAR(32) not null,
  user_id           CHAR(32) not null
)
;
alter table ECMS.US_MID_VIRTUAL_USER
  add constraint PK_US_MID_VIRTUAL_USER primary key (ID);

prompt Creating ECMS.US_ROLE...
create table ECMS.US_ROLE
(
  ID     CHAR(32) not null,
  NAME   VARCHAR2(60) not null,
  REMARK VARCHAR2(100 char)
)
;
alter table ECMS.US_ROLE
  add constraint PK_US_ROLE primary key (ID);

prompt Creating ECMS.US_MID_FUNCTION_ROLE...
create table ECMS.US_MID_FUNCTION_ROLE
(
  ID          CHAR(32) default SYS_guid() not null,
  ROLE_ID     CHAR(32) not null,
  FUNCTION_ID CHAR(32) not null
)
;
alter table ECMS.US_MID_FUNCTION_ROLE
  add constraint PK_US_MID_FUNCTION_ROLE primary key (ID);


prompt Creating ECMS.US_MID_METERTYPE_METERPAR...
create table ECMS.US_MID_METERTYPE_METERPAR
(
  ID           NUMBER not null,
  METERTYPE_ID CHAR(32) not null,
  METERPAR_ID  CHAR(32) not null
)
;
alter table ECMS.US_MID_METERTYPE_METERPAR
  add constraint PK_US_MID_METERTYPE_METERPAR primary key (ID);

prompt Creating ECMS.US_MID_ORG_PROPERTY...
create table ECMS.US_MID_ORG_PROPERTY
(
  PROPERTY_ID CHAR(32) not null,
  ORG_ID      CHAR(32) not null
)
;
alter table ECMS.US_MID_ORG_PROPERTY
  add primary key (ORG_ID, PROPERTY_ID);


prompt Creating ECMS.US_MID_USER_ROLE...
create table ECMS.US_MID_USER_ROLE
(
  ID      CHAR(32) default SYS_guid() not null,
  USER_ID CHAR(32) not null,
  ROLE_ID CHAR(32) not null
)
;
alter table ECMS.US_MID_USER_ROLE
  add constraint PK_US_MID_USER_ROLE primary key (ID);


prompt Creating ECMS.US_OLD_METER_INFO...
create table ECMS.US_OLD_METER_INFO
(
  ID                 CHAR(32) not null,
  ELEC_METER_ID      CHAR(32),
  WATER_METER_ID     CHAR(32),
  GAS_METER_ID       CHAR(32),
  WARM_METER_ID      CHAR(32),
  ZWJ_ID			 CHAR(32),
  CHANGE_TIME        CHAR(19),
  CHANGE_VALUE_TIME  CHAR(19),
  OLD_METER_DATA     NUMBER(11,3),
  NEW_METER_DATA     NUMBER(11,3),
  METER_SERIALNUMBER VARCHAR2(25),
  BAUD_BIT           NUMBER(6),
  STOP_BIT           NUMBER(1),
  CHECK_BIT          NUMBER(1),
  METER_ADDR         VARCHAR2(16),
  DATA_BIT           NUMBER(10)
)
;
alter table ECMS.US_OLD_METER_INFO
  add constraint PK_US_OLD_METER_INFO primary key (ID);


prompt Creating ECMS.US_RUNTIME_PAR...
create table ECMS.US_RUNTIME_PAR
(
  ID         CHAR(32) not null,
  USER_ID    CHAR(32),
  PAR_NAME   VARCHAR2(60) not null,
  PAR_TYPE   NUMBER(4) not null,
  PAR_VALUE  VARCHAR2(60) not null,
  IS_DISABLE CHAR(1)
)
;
alter table ECMS.US_RUNTIME_PAR
  add constraint PK_US_RUNTIME_PAR primary key (ID);

prompt Creating ECMS.US_SHORTCUT_MENU...
create table ECMS.US_SHORTCUT_MENU
(
  ID          NUMBER not null,
  USER_ID     CHAR(32) not null,
  FUNCTION_ID CHAR(32) not null
)
;
alter table ECMS.US_SHORTCUT_MENU
  add constraint PK_US_SHORTCUT_MENU primary key (ID);


prompt Creating ECMS.US_TIMETASK...
create table ECMS.US_TIMETASK
(
  ID       CHAR(32) not null,
  TIME     VARCHAR2(30) not null,
  REMARK   VARCHAR2(50),
  NEXTTIME NUMBER(3)
)
;
alter table ECMS.US_TIMETASK
  add primary key (ID);

prompt Creating ECMS.US_VIRTUAL_COMPUTE...
create table ECMS.US_VIRTUAL_COMPUTE
(
  ID                     CHAR(32) not null,
  ELEC_VIRTUAL_METER_ID  CHAR(32),
  WATER_VIRTUAL_METER_ID CHAR(32),
  WARM_VIRTUAL_METER_ID  CHAR(32),
  GAS_VIRTUAL_METER_ID   CHAR(32),
  ELEC_REAL_METER_ID     CHAR(32),
  WATER_REAL_METER_ID    CHAR(32),
  WARM_REAL_METER_ID     CHAR(32),
  GAS_REAL_METER_ID      CHAR(32),
  COMPUTE_TYPE           NUMBER(1)
)
;
alter table ECMS.US_VIRTUAL_COMPUTE
  add constraint PK_US_COMPUTE_VIRTUALMETER primary key (ID);

prompt Creating ECMS.US_VIRTUAL_COMPUTE... 
create table ECMS.US_ENERGY_LIMIT_ALARM
(
  ID           CHAR(32) not null,
  ADDR_ID      CHAR(32),
  ORG_ID       CHAR(32),
  MORE_OR_LESS NUMBER(1),
  BEGIN_HOUR   NUMBER(2),
  END_HOUR     NUMBER(2),
  ALARM_VALUE  NUMBER(13,3),
  CLASSIFY     NUMBER(1),
  LAST_TIME    CHAR(19)
)
;
alter table ECMS.US_ENERGY_LIMIT_ALARM
  add constraint PK_US_ENERGY_LIMIT_ALARM  primary key (ID); 
  
prompt Creating ECMS.US_ORGAN_QUOTA...
create table ECMS.US_ORGAN_QUOTA
(
  ID                     CHAR(32) not null,
  ORG_ID				 CHAR(32),
  YEAR					 CHAR(4),
  ELEC_QUOTA             NUMBER(11,3),
  CREATE_DATE            CHAR(19),
  MODIFY_DATE            CHAR(19),
  IS_CONFIRM             CHAR(1),
  DATA_TYPE              NUMBER(1),
  TOTAL_ELEC_QUOTA       NUMBER(12,3)
)
;
alter table ECMS.US_ORGAN_QUOTA
  add constraint PK_US_ORGAN_QUOTA primary key (ID);
  
prompt Creating ECMS.US_ORGAN_ADD_QUOTA...
create table ECMS.US_ORGAN_ADD_QUOTA
(
  ID                     CHAR(32) not null,
  QUOTA_ID				 CHAR(32),
  ADD_TIMES			     NUMBER(4),
  ADD_QUOTA              NUMBER(11,3),
  CREATE_DATE            CHAR(19),
  IS_CONFIRM             CHAR(1)
)
;
alter table ECMS.US_ORGAN_ADD_QUOTA
  add constraint PK_US_ORGAN_ADD_QUOTA primary key (ID);
  
prompt Creating ECMS.US_MODIFY_QUOTA_RECORD...
create table ECMS.US_MODIFY_QUOTA_RECORD
(
  ID                     CHAR(32) not null,
  QUOTA_ID				 CHAR(32),
  MODIFY_DATE            CHAR(19),
  USER_ID                CHAR(32),
  BEFORE_QUOTA           NUMBER(12,3),
  MODIFY_QUOTA           NUMBER(12,3)
)
;
alter table ECMS.US_MODIFY_QUOTA_RECORD
  add constraint PK_US_MODIFY_QUOTA_RECORD primary key (ID);
  
prompt Creating ECMS.US_UDP_INFO...
create table ECMS.US_UDP_INFO
(
  PK_UDP_INFO  CHAR(32) not null,
  GATEWAY_ID   CHAR(32),
  IP_ADDRESS   VARCHAR2(15),
  REMOTEPORT   NUMBER(5),
  LOCALPORT    NUMBER(5),
  DISABLED     CHAR(1),
  INTERMISSION NUMBER(3),
  TOGATEWAY    CHAR(1)
); 
alter table US_UDP_INFO
  add constraint PK_US_UDP_INFO primary key (PK_UDP_INFO);
  
 prompt Creating ECMS.US_MID_MAPADDR_PLATFORMADDR...
create table ECMS.US_MID_MAPADDR_PLATFORMADDR
(
  ID          CHAR(32) not null,
  ADDR_NUMBER VARCHAR2(4),
  ADDR_ID     CHAR(32),
  ADDR_NAME   VARCHAR2(50 CHAR)
)
;
alter table US_MID_MAPADDR_PLATFORMADDR
  add primary key (ID);
  
  
  
prompt Creating ECMS.US_OPERATE_LOG...
CREATE TABLE ECMS.US_OPERATE_LOG 
(
  ID char(32) NOT NULL 
, OPERATE_TIME VARCHAR2(19)
, OPERATOR char(32) 
, OPERATE_CONTENT VARCHAR2(250 char) 
);
alter table ECMS.US_OPERATE_LOG
  add constraint PK_US_OPERATE_LOG  primary key (ID); 

prompt Creating ECMS.US_METER_PROPERTYTYPE...
create table ECMS.US_METER_PROPERTYTYPE
(
  ID          CHAR(32) not null,
  SHOWNAME    VARCHAR2(60)
);
alter table ECMS.US_METER_PROPERTYTYPE
  add constraint PK_US_METER_PROPERTYTYPE primary key (ID);
  
prompt Creating ECMS.US_ENERGY_SCORE_INFOR...
create table ECMS.US_ENERGY_SCORE_INFOR
(
  ID                         CHAR(32) not null,
  WATER_DEVICE               NUMBER(3),
  ELEC_DEVICE                NUMBER(3),
  ENERGY_DEVICE              NUMBER(3),
  IN_DEVICE                  NUMBER(3),
  COLLEGE_ELEC_DEVICE        NUMBER(3),
  COLLEGE_WATER_DEVICE       NUMBER(3),
  STUDENT_ELEC_DEVICE        NUMBER(3),
  STUDENT_WATER_DEVICE       NUMBER(3),
  SCHOOL_ELEC_DEVICE         NUMBER(3),
  SCHOOL_WATER_DEVICE        NUMBER(3),
  INWATER_DEVICE             NUMBER(3),
  SOLAR_ELEC_SYSTEM          NUMBER(3),
  SOLAR_WATER_SYSTEM         NUMBER(3),
  OTHER_ENERGY               NUMBER(3),
  PROJECT_EXAMINE_SYSTEM     NUMBER(3),
  FACILITY_EXAMINE_SYSTEM    NUMBER(3),
  STATISTICS_EXAMINE_SYSTEM  NUMBER(3),
  DATASHARE_EXAMINE_SYSTEM   NUMBER(3),
  DEMAND_EXAMINE_SYSTEM      NUMBER(3),
  PURCHASE_EXAMINE_SYSTEM    NUMBER(3),
  ENVIRONMENT_EXAMINE_SYSTEM NUMBER(3),
  SET_LEVELSCHARGE_PERSON    NUMBER(3),
  SET_SCHOOLCHARGE_PERSON    NUMBER(3),
  SET_SCHOOL_CMC             NUMBER(3),
  CHARGE_PERSON_QUALITIES    NUMBER(3),
  ELEC_SAVING_EFFECT         NUMBER(3),
  WATER_SAVING_EFFECT        NUMBER(3),
  WARM_SAVING_EFFECT         NUMBER(3),
  INWATER_RATE               NUMBER(3),
  OTHER_SAVING_EFFECT        NUMBER(3),
  NEW_SYSTEM_IMPLEMENT       NUMBER(3),
  EDIT_SYSTEM_IMPLEMENT      NUMBER(3),
  RUN_SYSTEM_IMPLEMENT       NUMBER(3),
  MONITOR_SYSTEM_IMPLEMENT   NUMBER(3),
  TEACHING_ADDR_MEASURE      NUMBER(3),
  OFFICE_ADDR_MEASURE        NUMBER(3),
  RESEARCH_ADDR_MEASURE      NUMBER(3),
  STUDENT_ADDR_MEASURE       NUMBER(3),
  CANTEEN_ADDR_MEASURE       NUMBER(3),
  CLASS_AND_LECTURE          NUMBER(3),
  RESEARCH_AND_PRACTICE      NUMBER(3),
  PROPAGANDA_AND_UNIVERSAL   NUMBER(3)
);
prompt
prompt Creating table BS_ORIGINALDATA_BF
prompt =================================
prompt
create table ECMS.BS_ORIGINALDATA_BF
(
  DATA_ID            CHAR(32) not null,
  ELEC_METER_ID      CHAR(32),
  COL_DATE           VARCHAR2(19) not null,
  REPORT_DATE        VARCHAR2(19) not null,
  DATA_DATE          VARCHAR2(19),
  IS_NEW             CHAR(1),
  WATER_METER_ID     CHAR(32),
  WARM_METER_ID      CHAR(32),
  GAS_METER_ID       CHAR(32),
  ERROR_COUNTER      NUMBER(4),
  RIGHT_COUNTER      NUMBER(4),
  TOTAL_USED         NUMBER(13,3),
  TOTAL_BUY          NUMBER(13,3),
  VOLTAGE            NUMBER(4,1),
  ELECTRIC_CURRENT   NUMBER(8,3),
  POWER              NUMBER(10,4),
  A_VOLTAGE          NUMBER(4,1),
  B_VOLTAGE          NUMBER(4,1),
  C_VOLTAGE          NUMBER(4,1),
  A_ELECTRIC_CURRENT NUMBER(8,3),
  B_ELECTRIC_CURRENT NUMBER(8,3),
  C_ELECTRIC_CURRENT NUMBER(8,3),
  A_POWER            NUMBER(7,4),
  B_POWER            NUMBER(7,4),
  C_POWER            NUMBER(7,4),
  BATCHNO            CHAR(32)
)
;  
  
prompt
prompt Creating table BS_WARMMETER_ORIDATA
prompt ===================================
prompt
create table ECMS.BS_WARMMETER_ORIDATA
(
  ID           CHAR(32) not null,
  SERIALNUMBER VARCHAR2(5),
  TOTAL_USED   NUMBER(13,3),
  DATA_TIME    CHAR(19),
  IS_NEW       CHAR(1),
  COL_DATE     CHAR(19)
)
;
alter table BS_WARMMETER_ORIDATA
  add constraint PK_ID primary key (ID);
  
prompt
prompt Creating table DELETE_ELEC
prompt ==========================
prompt
create table ECMS.DELETE_ELEC
(
  ELEC_METER_ID CHAR(32),
  DATA_DATE     VARCHAR2(19)
)
;

prompt
prompt Creating table DELETE_WATER
prompt ===========================
prompt
create table ECMS.DELETE_WATER
(
  WATER_METER_ID CHAR(32),
  DATA_DATE      VARCHAR2(19)
)
;    

prompt
prompt Creating table US_CHANGE_METER_ORG
prompt ==================================
prompt
create table ECMS.US_CHANGE_METER_ORG
(
  ID             CHAR(32) not null,
  EFFECTIVE_TIME CHAR(19),
  ORG_ID         CHAR(32) not null,
  PRE_METER_IDS  VARCHAR2(1000),
  NEW_METER_IDS  VARCHAR2(1000)
)
;
alter table US_CHANGE_METER_ORG
  add primary key (ID);

prompt
prompt Creating table US_ENERGY_FORECASTING_PARA
prompt =========================================
prompt
create table ECMS.US_ENERGY_FORECASTING_PARA
(
  ID            CHAR(32),
  JAN_AREA      NUMBER(12,2),
  JAN_PEOCOUNT  NUMBER(10),
  FEB_AREA      NUMBER(12,2),
  FEB_PEOCOUNT  NUMBER(10),
  MAR_AREA      NUMBER(12,2),
  MAR_PEOCOUNT  NUMBER(10),
  APR_AREA      NUMBER(12,2),
  APR_PEOCOUNT  NUMBER(10),
  MAY_AREA      NUMBER(12,2),
  MAY_PEOCOUNT  NUMBER(10),
  JUNE_AREA     NUMBER(12,2),
  JUNE_PEOCOUNT NUMBER(10),
  JULY_AREA     NUMBER(12,2),
  JULY_PEOCOUNT NUMBER(10),
  AUG_AREA      NUMBER(12,2),
  AUG_PEOCOUNT  NUMBER(10),
  SEPT_AREA     NUMBER(12,2),
  SEPT_PEOCOUNT NUMBER(10),
  OCT_AREA      NUMBER(12,2),
  OCT_PEOCOUNT  NUMBER(10),
  NOV_AREA      NUMBER(12,2),
  NOV_PEOCOUNT  NUMBER(10),
  DEC_AREA      NUMBER(12,2),
  DEC_PEOCOUNT  NUMBER(10),
  COEFFICIENT   NUMBER(3,2)
)
;  
 
prompt
prompt Creating table US_ENERGY_NOTICE
prompt ===============================
prompt
create table ECMS.US_ENERGY_NOTICE
(
  ID          CHAR(32) not null,
  ORG_ID      CHAR(32),
  COAL_ALL    NUMBER(18,4),
  COAL_AREA   NUMBER(18,4),
  COAL_PEOPEL NUMBER(18,4),
  COAL_ODDS   NUMBER(8,3),
  ELEC_ALL    NUMBER(18,4),
  ELEC_AREA   NUMBER(18,4),
  ELEC_PEOPEL NUMBER(18,4),
  ELEC_ODDS   NUMBER(8,3),
  HOT_ALL     NUMBER(18,4),
  HOT_AREA    NUMBER(18,4),
  HOT_PEOPEL  NUMBER(18,4),
  HOT_ODDS    NUMBER(8,3),
  YEAR        NUMBER(4),
  MONTH       NUMBER(2),
  MONTH_MONEY NUMBER(14,2)
)
;
alter table US_ENERGY_NOTICE
  add constraint PK_US_ENERGY_NOTICE primary key (ID);
alter table US_ENERGY_NOTICE
  add constraint FK42C9688EA8AAFA2E foreign key (ORG_ID)
  references US_ORGAN_INFOR (ORG_ID);
  
prompt
prompt Creating table US_ORG_WATERVALUE_INFOR
prompt ======================================
prompt
create table ECMS.US_ORG_WATERVALUE_INFOR
(
  ID                  CHAR(32) not null,
  TIME                CHAR(7),
  TOTAL_WATER_USED    NUMBER(17,3),
  ORG_ID              CHAR(32),
  INCRATE_RATE        NUMBER(11,3),
  WATER_USED_BYAREA   NUMBER(17,3),
  WATER_USED_BYPEOPLE NUMBER(17,3)
);

alter table US_ORG_WATERVALUE_INFOR
  add primary key (ID);
  
prompt
prompt Creating table US_SCHOOL_GREEN_AREA
prompt ===================================
prompt
create table ECMS.US_SCHOOL_GREEN_AREA
(
  ID                     CHAR(32),
  BROAD_DECIDUOUS_FOREST NUMBER(11,2),
  BROAD_EVERGREEN_FOREST NUMBER(11,2),
  CONIFEROUS_FOREST      NUMBER(11,2),
  BUSHWOOD               NUMBER(11,2),
  LAWN                   NUMBER(11,2),
  WEEK_TARGET            NUMBER(3),
  MONTH_TARGET           NUMBER(3),
  YEAR_TARGET            NUMBER(3)
)
;
alter table ECMS.US_ENERGY_SCORE_INFOR
  add constraint PK_US_ENERGY_SCORE_INFOR primary key (ID);
  
prompt Creating ECMS.US_PERSONNEL_INFOR...
create table ECMS.US_PERSONNEL_INFOR
(
  PERSONNEL_ID             	CHAR(32) not null,
  NAME              		VARCHAR2(20) not null,
  PERSONNEL_NUMBER          VARCHAR2(20) not null,
  IDENTITY           		VARCHAR2(20) not null,
  PHONE_NUM                 VARCHAR2(15),
  ADDR_ID             		CHAR(32),
  ORG_ID        			CHAR(32)
)
;
alter table ECMS.US_PERSONNEL_INFOR
  add constraint PK_US_PERSONNEL_INFOR primary key (PERSONNEL_ID);
  
prompt Creating ECMS.US_EQUIPMENT_INFOR...
create table ECMS.US_EQUIPMENT_INFOR
(
  EQUIPMENT_ID             	CHAR(32) not null,
  NAME              		VARCHAR2(50) not null,
  EQUIPMENT_NUM				VARCHAR2(4),
  MODEL            			VARCHAR2(50) ,
  SPECIFICATION           	VARCHAR2(50) ,
  BRANDS             		VARCHAR2(50) ,
  USE        				VARCHAR2(50) ,
  POWER						NUMBER(10,2),
  ADDR_ID             		CHAR(32),
  ORG_ID        			CHAR(32),
  PERSONNEL_ID        		CHAR(32),
  REMARK					VARCHAR2(100),
  CREATE_DATE               CHAR(19),
  MODIFY_DATE               CHAR(19)
)
;
alter table ECMS.US_EQUIPMENT_INFOR
  add constraint PK_US_EQUIPMENT_INFOR primary key (EQUIPMENT_ID);  

prompt Creating ECMS.US_ACCOUNT_INFOR...
create table ECMS.US_ACCOUNT_INFOR
(
  ID             			CHAR(32) not null,
  NAME              		VARCHAR2(50) not null,
  REMARK					VARCHAR2(100) ,
  ACCOUNT_NUMBER 			VARCHAR2(20) not null
)
;
alter table ECMS.US_ACCOUNT_INFOR
  add constraint PK_US_ACCOUNT_INFOR primary key (ID);   
  
prompt Creating ECMS.US_REPORT_SET...  
create table ECMS.US_REPORT_SET
(
  ID             			CHAR(32) not null,
  NAME              		VARCHAR2(50) not null,
  DAY_NUMBER          		NUMBER(4),
  PERSON_NAME           	VARCHAR2(100),
  PHONE             		VARCHAR2(30)
)
;
alter table ECMS.US_REPORT_SET
  add constraint PK_US_REPORT_SET primary key (ID);  
  
prompt Creating ECMS.US_EXPERTADVICE_INFOR...
create table ECMS.US_EXPERTADVICE_INFOR
(
  ID             			CHAR(32) not null,
  SUPER_ID              	CHAR(32) ,
  ADVICE_NAME				VARCHAR2(100),
  ANSWER                    VARCHAR2(100 CHAR)
)
;
alter table ECMS.US_EXPERTADVICE_INFOR
  add constraint PK_US_EXPERTADVICE_INFOR primary key (ID);
 
prompt Creating ECMS.US_SCHOOL_INFO...
create table ECMS.US_SCHOOL_INFO
(
 SCHOOL_ID             CHAR(32) not null,
 SCHOOL_NAME           VARCHAR2(50),
 SCHOOL_LOGO           VARCHAR2(200),
 SCHOOL_OVERREAD_IMG   VARCHAR2(200),
 SCHOOL_OVERVIEW_IMG   VARCHAR2(200),
 SCHOOL_DESCRIBE       VARCHAR2(1000 CHAR)
)
;
alter table ECMS.US_SCHOOL_INFO
  add constraint PK_US_SCHOOL_INFO primary key (SCHOOL_ID);


prompt Creating ECMS.US_QUOTA...
create table ECMS.US_QUOTA
(
  ID                     CHAR(32) not null,
  ORG_ID				 CHAR(32),
  YEAR					 CHAR(4),
  ORIGINAL_QUOTA         NUMBER(12,3),
  CREATE_DATE            CHAR(19),
  MODIFY_DATE            CHAR(19),
  IS_CONFIRM             CHAR(1),
  OFFICIAL_QUOTA         NUMBER(12,3)
)
;
alter table ECMS.US_QUOTA
  add constraint PK_US_QUOTA primary key (ID);
 
  
prompt Creating ECMS.US_MODIFY_QUOTA...
create table ECMS.US_MODIFY_QUOTA
(
  ID                     CHAR(32) not null,
  ORG_ID				 CHAR(32),
  YEAR     				 CHAR(4),
  MODIFY_DATE            CHAR(19),
  USER_ID                CHAR(32),
  BEFORE_QUOTA           NUMBER(12,3),
  MODIFY_QUOTA           NUMBER(12,3)
)
;
alter table ECMS.US_MODIFY_QUOTA
  add constraint PK_US_MODIFY_QUOTA primary key (ID);

prompt Creating ECMS.US_MAPSET_INFOR...
create table ECMS.US_MAPSET_INFOR
(
  MAPSET_ID              CHAR(32) not null,
  MAPSET_NAME     		 VARCHAR2(20 CHAR),
  IS_SELECTED            CHAR(1)
)
;
alter table ECMS.US_MAPSET_INFOR
  add constraint PK_US_MAPSET_INFOR primary key (MAPSET_ID);
  
prompt Creating ECMS.US_METER_CONTROL...
create table ECMS.US_METER_CONTROL
(
  ID          CHAR(32) not null,
  METER_ID    CHAR(32) 
)
;
alter table ECMS.US_METER_CONTROL
  add constraint PK_US_METER_CONTROL primary key (ID);

prompt Creating ECMS.US_TIMINGCONTROL_SET_INFOR...
 CREATE TABLE ECMS.US_TIMINGCONTROL_SET_INFOR
(
   TIMINGCONTROL_ID CHAR(32) NOT NULL,
   ELECMETER_ID CHAR(32),
   WEEKTIME NUMBER(1),
   BEGINHOUR  CHAR(2),
   BEGINMIN   CHAR(2),
   ENDHOUR  CHAR(2),
   ENDMIN CHAR(2)
)
;
ALTER TABLE ECMS.US_TIMINGCONTROL_SET_INFOR ADD CONSTRAINT PK_US_TIMINGCONTROL_SET_INFOR
     PRIMARY KEY (TIMINGCONTROL_ID);

 
drop index uidx_BS_ORI_ELEC_METER_ID;
Create  index uidx_BS_ORI_ELEC_METER_ID on BS_ORIGINALDATA(ELEC_METER_ID) tablespace ECMS_INDEX ; 

drop index uidx_BS_ORI_WATER_METER_ID;
Create  index uidx_BS_ORI_WATER_METER_ID on BS_ORIGINALDATA(WATER_METER_ID) tablespace ECMS_INDEX ; 

drop index uidx_bs_tre_ELEC_METER_ID;
Create  index uidx_bs_tre_ELEC_METER_ID on bs_treateddata(ELEC_METER_ID) tablespace ECMS_INDEX ;

drop index uidx_bs_tre_WATER_METER_ID;
Create  index uidx_bs_tre_WATER_METER_ID on bs_treateddata(WATER_METER_ID) tablespace ECMS_INDEX ;

drop index uidx_bs_tre_elec_DATE;
Create  index uidx_bs_tre_elec_DATE on bs_treateddata(ELEC_METER_ID,TREATE_DATE) tablespace ECMS_INDEX ;

drop index uidx_bs_tre_water_DATE;
Create  index uidx_bs_tre_water_DATE on bs_treateddata(WATER_METER_ID,TREATE_DATE) tablespace ECMS_INDEX ;

drop index uidx_bs_INC_ELEC_METER_ID;
Create  index uidx_bs_INC_ELEC_METER_ID on BS_INCREMENT_DATA(ELEC_METER_ID) tablespace ECMS_INDEX ;

drop index uidx_bs_INC_WATER_METER_ID;
Create  index uidx_bs_INC_WATER_METER_ID on BS_INCREMENT_DATA(WATER_METER_ID) tablespace ECMS_INDEX ;

drop index uidx_bs_INC_elec_TIME;
Create  index uidx_bs_INC_elec_TIME on BS_INCREMENT_DATA(ELEC_METER_ID,DATA_TIME) tablespace ECMS_INDEX ;

drop index uidx_bs_INC_water_TIME;
Create  index uidx_bs_INC_water_TIME on BS_INCREMENT_DATA(WATER_METER_ID,DATA_TIME) tablespace ECMS_INDEX ;

drop index uidx_BS_VIR_error_TRE_ID;
Create  index uidx_BS_VIR_error_TRE_ID on BS_VIRTUAL_ERROR_METER(TREATED_DATA_ID) tablespace ECMS_INDEX ;

drop index uidx_BS_VIR_er_ELEC_METER_ID;
Create  index uidx_BS_VIR_er_ELEC_METER_ID on BS_VIRTUAL_ERROR_METER(ELEC_METER_ID) tablespace ECMS_INDEX ;

drop index uidx_BS_VIR_er_WATER_METER_ID;
Create  index uidx_BS_VIR_er_WATER_METER_ID on BS_VIRTUAL_ERROR_METER(WATER_METER_ID) tablespace ECMS_INDEX ;


/**教室照明部分开始
**/
DROP TABLE BS_JSZM_OFFICIAL_DATA CASCADE CONSTRAINTS
;
DROP TABLE BS_JSZM_OPERATING_LOG CASCADE CONSTRAINTS
;
DROP TABLE BS_JSZM_ORIGINAL_DATA CASCADE CONSTRAINTS
;
DROP TABLE SYS_JSZM_DEVICE_TYPE CASCADE CONSTRAINTS
;
DROP TABLE US_JSZM_CLASSROOM_AREA CASCADE CONSTRAINTS
;
DROP TABLE US_JSZM_CLASSROOM_INFOR CASCADE CONSTRAINTS
;
DROP TABLE US_JSZM_CONTROLLER_INFOR CASCADE CONSTRAINTS
;
DROP TABLE US_JSZM_GAMETHEORY_INFOR CASCADE CONSTRAINTS
;
DROP TABLE US_JSZM_SENSOR_INFOR CASCADE CONSTRAINTS
;
DROP TABLE US_JSZM_SLAVE_INFOR CASCADE CONSTRAINTS
;
DROP TABLE BS_MID_GATEWAY_BATCH_JSZM CASCADE CONSTRAINTS
;

CREATE TABLE BS_JSZM_OFFICIAL_DATA
(
	DATA_ID             CHAR(32) NOT NULL,    
	GATHER_TIME         CHAR(19),    
	CONTROLLER_ID       CHAR(32),    
	SLAVE_ID            CHAR(32),    
	SENSOR_ID           CHAR(32),    
	ILLUMINATION_TOTAL  NUMBER(4),    
	LIGHTS_RATE         NUMBER(6,2),    
	IS_HAVE_PEOPLE      CHAR(1),    
	OFF_STATE           CHAR(1),   
	LIGHTS_AREA_TOTAL   NUMBER(2),   
	LIGHTS_TOTAL        NUMBER(3),   
	FAULT_STATE         CHAR(1)    
)
;
ALTER TABLE BS_JSZM_OFFICIAL_DATA ADD CONSTRAINT PK_BS_DATA 
	PRIMARY KEY (DATA_ID)
;


CREATE TABLE BS_JSZM_OPERATING_LOG
(
	LOG_ID            CHAR(32) NOT NULL,  
	OPERATING_DATE    CHAR(19),   
	OPERATING_REMARK  VARCHAR2(200),  
	NODE_ID           CHAR(32)  
)
;
ALTER TABLE BS_JSZM_OPERATING_LOG ADD CONSTRAINT PK_BS_OPERATING_LOG 
	PRIMARY KEY (LOG_ID)
;


CREATE TABLE BS_JSZM_ORIGINAL_DATA
(
	ORIGINAL_ID         CHAR(32) NOT NULL,    
	SLAVE_STATE         VARCHAR(20),    
	SENSOR_FAULT        VARCHAR(16),   
	SLAVE_FAULT         VARCHAR(20),   
	ILLUMINATION_TOTAL  NUMBER(3),    
	GATHER_TIME         CHAR(19),    
	CONTROLLER_ID       CHAR(32),    
	IS_HAVE_PEOPLE      CHAR(1),  
	OFF_STATE           NUMBER(1),
	IS_HANDLE           CHAR(1) ,
	IS_ERROR			      NUMBER(1)
)
;
ALTER TABLE BS_JSZM_ORIGINAL_DATA ADD CONSTRAINT PK_BS_JSZM_ORIGINAL_DATA 
	PRIMARY KEY (ORIGINAL_ID)
;


CREATE TABLE SYS_JSZM_DEVICE_TYPE
(
	DEVICE_ID    CHAR(32) NOT NULL,     
	DEVICE_NAME  VARCHAR2(50),   
	DEVICE_TYPE  CHAR(1)     
)
;
ALTER TABLE SYS_JSZM_DEVICE_TYPE ADD CONSTRAINT PK_SYS_JSZM_DEVICE_TYPE 
	PRIMARY KEY (DEVICE_ID)
;


CREATE TABLE US_JSZM_CLASSROOM_AREA
(
	AREA_ID       CHAR(32) NOT NULL,   
	CLASSROOM_ID  CHAR(32),    
	AREA_NAME     VARCHAR2(10),    
	LAMPS_TOTAL   NUMBER(2),     
	LIGHT_POWER   NUMBER(7,2)   
)
;
ALTER TABLE US_JSZM_CLASSROOM_AREA ADD CONSTRAINT PK_US_CLASSROOM_AREA 
	PRIMARY KEY (AREA_ID)
;


CREATE TABLE US_JSZM_CLASSROOM_INFOR
(
	CLASSROOM_ID  CHAR(32) NOT NULL,    
	ADDR_ID       CHAR(32),    
	CAPACITY      NUMBER(4),     
	AREANUMBER    NUMBER(2),     
	LIGHTSNUMBER  NUMBER(3),  
	CREATEDATE    VARCHAR2(19), 
	MODIFYDATE    VARCHAR2(19)
)
;
ALTER TABLE US_JSZM_CLASSROOM_INFOR ADD CONSTRAINT PK_US_JSZM_CLASSROOM_INFOR 
	PRIMARY KEY (CLASSROOM_ID)
;


CREATE TABLE US_JSZM_CONTROLLER_INFOR
(
	CONTROLLER_ID    CHAR(32) NOT NULL,    
	CONTROLLER_NAME  VARCHAR2(50),     
	CONTROLLER_NUM   CHAR(4),     
	CONTROLLER_TYPE  CHAR(32),   
	CLASSROOM_ID     CHAR(32),    
	GATEWAY_ID       CHAR(32),    
	COM_ID			     CHAR(32),
	IS_SYNCHRONOUS   CHAR(1),     
	CONTROLLER_ADDR  CHAR(3),    
	CREATEDATE       VARCHAR2(19), 
	MODIFYDATE       VARCHAR2(19),   
	IS_DISABLE       CHAR(1),       
	BAUD_BIT         NUMBER(6)
)
;
ALTER TABLE US_JSZM_CONTROLLER_INFOR ADD CONSTRAINT PK_US_JSZM_CONTROLLER_INFOR
	PRIMARY KEY (CONTROLLER_ID)
;


CREATE TABLE US_JSZM_GAMETHEORY_INFOR
(
	GAMETHEORY_ID               CHAR(32) NOT NULL,    
	CONTROLLER_ID               CHAR(32),
	SUMMER_BEGIN_MONTH          CHAR(2), 
	SUMMER_BEGIN_DAY            CHAR(2),
	SUMMER_END_MONTH            CHAR(2), 
	SUMMER_END_DAY              CHAR(2),
	SUMMER_MORNING_BEGINHOUR    CHAR(2), 
	SUMMER_MORNING_BEGINMIN     CHAR(2),
	SUMMER_MORNING_ENDHOUR      CHAR(2), 
	SUMMER_MORNING_ENDMIN       CHAR(2),
	SUMMER_AFTERNOON_BEGINHOUR  CHAR(2), 
	SUMMER_AFTERNOON_BEGINMIN   CHAR(2),
	SUMMER_AFTERNOON_ENDHOUR    CHAR(2), 
	SUMMER_AFTERNOON_ENDMIN     CHAR(2),
	SUMMER_NIGHT_BEGINHOUR      CHAR(2), 
	SUMMER_NIGHT_BEGINMIN       CHAR(2),
	SUMMER_NIGHT_ENDMIN         CHAR(2),
	SUMMER_NIGHT_ENDHOUR        CHAR(2),
	WINTER_BEGIN_MONTH          CHAR(2), 
	WINTER_BEGIN_DAY            CHAR(2),
	WINTER_END_MONTH            CHAR(2), 
	WINTER_END_DAY              CHAR(2),
	WINTER_MORNING_BEGINHOUR    CHAR(2), 
	WINTER_MORNING_BEGINMIN     CHAR(2),
	WINTER_MORNING_ENDHOUR      CHAR(2), 
	WINTER_MORNING_ENDMIN       CHAR(2),
	WINTER_AFTERNOON_BEGINHOUR  CHAR(2), 
	WINTER_AFTERNOON_BEGINMIN   CHAR(2),
	WINTER_AFTERNOON_ENDHOUR    CHAR(2), 
	WINTER_AFTERNOON_ENDMIN     CHAR(2),
	WINTER_NIGHT_BEGINHOUR      CHAR(2), 
	WINTER_NIGHT_BEGINMIN       CHAR(2),
	WINTER_NIGHT_ENDHOUR        CHAR(2), 
	WINTER_NIGHT_ENDMIN         CHAR(2),
	ILLUMINATION_OPEN           NUMBER(4),
	ILLUMINATION_CLOSE          NUMBER(4),
	BACKLASH_TOTAL              NUMBER(4),
	ILLUMINATION_DELAY          NUMBER(3)
)
;
ALTER TABLE US_JSZM_GAMETHEORY_INFOR ADD CONSTRAINT PK_US_JSZM_GAMETHEORY_INFOR
	PRIMARY KEY (GAMETHEORY_ID)
;


CREATE TABLE US_JSZM_SENSOR_INFOR
(
	SENSOR_ID      CHAR(32) NOT NULL,
	SENSOR_NUMBER  CHAR(3),    
	SENSOR_ADDR    CHAR(2),    
	SENSOR_TYPE    CHAR(32),     
	SENSOR_NO      CHAR(8),     
	CONTROLER_ID   CHAR(32),    
	SENSOR_NAME    VARCHAR2(50),     
	AREA_ID        CHAR(32),
	CREATEDATE     VARCHAR2(19), 
	MODIFYDATE     VARCHAR2(19),   
	IS_DISABLE     CHAR(1)
)
;

ALTER TABLE US_JSZM_SENSOR_INFOR ADD CONSTRAINT PK_US_JSZM_SENSOR_INFOR
	PRIMARY KEY (SENSOR_ID)
;


CREATE TABLE US_JSZM_SLAVE_INFOR
(
	SLAVE_ID       CHAR(32) NOT NULL,   
	SLAVE_ADDR     CHAR(3),    
	SLAVE_NUMBER   CHAR(3),	   
	SLAVE_NO       CHAR(8),     
	SLAVE_TYPE     CHAR(32),    
	CONTROLLER_ID  CHAR(32),     
	SLAVE_NAME     VARCHAR2(50),
	AREA_ID        CHAR(32),
	CREATEDATE     VARCHAR2(19),
	MODIFYDATE     VARCHAR2(19),   
	IS_DISABLE     CHAR(1)
)
;
ALTER TABLE US_JSZM_SLAVE_INFOR ADD CONSTRAINT PK_US_JSZM_SLAVE_INFOR
	PRIMARY KEY (SLAVE_ID)
;


create table BS_MID_GATEWAY_BATCH_JSZM
(
  ID         CHAR(32) not null,
  GATEWAY_ID CHAR(32),
  BATCH      VARCHAR2(32)
);
alter table BS_MID_GATEWAY_BATCH_JSZM
  add constraint PK_BS_MID_GATEWAY_BATCH_JSZM primary key (ID);

/**教室照明部分结束
**/
spool off